### PR TITLE
Removed sex/gender field in profile.

### PR DESCRIPTION
**Pull request by juniperbelmont**
Removed the binary option for gender. Gender is not a boolean.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/dashboard-demo/9)

### CODE REVIEW

**Comment by jouni** [comment]
Thanks! I have completely missed this PR.

This change should actually be made in our Gerrit. This GitHub repo is just a replication of that repository: https://dev.vaadin.com/review/#/admin/projects/dashboard-demo

**Comment by elmot** [comment]
We need some example of boolean field. Any ideas what type of the information could be used for that instead of gender?

**Comment by cisko3000** [comment]
Where is the boolean going to be located again?
Here are some ideas out of context
Booleans:
Organ donor
Disabled
Over 21
Senior
Native American
Veteran
Subscribe to newsletter


Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by jouni** [comment]
> Where is the boolean going to be located again?

In the “Edit Profile” dialog (click the profile picture in the sidebar): 

screen shot 2017-05-02 at 10 15 09

There’s already a “Subscribe to newsletter” option there, so that’s not good.

The boolean could be moved down to the “Contact info” section, something like “Allow 3rd party marketing”.

**Comment by caiwan** [comment]
I suggest to make a good example for  table connections, and dropdown lists to store and list all the known non-binary genders by the society [like so](http://genderfluidsupport.tumblr.com/gender/).

**Comment by jforge** [comment]
The OptionGroup could be improved instead of being deleted.
Gender should be some (open) enumeration with some Options.

Due to at least 60 different gender identities (AFAIK), we could make a compromise and use some well-known definition of Gender, e.g.: Gender := undetermined, trans/inter, female, male.

This would be a good use-case for the demonstrating the OptionGroup.

**Comment by elmot** [comment]
Closed due to inactivity

**Pull request closed without merging**
